# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuumcoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_value',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
