# Generated by Django 2.2 on 2019-04-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuumcoin', '0003_coin_total_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_percent', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
